name: Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qt:
          - target: wasm
            arch: wasm_singlethread
          - target: android
            arch: android_arm64_v8a
    steps:        
      - uses: jurplel/install-qt-action@v4.4.1
        with:
          version: '6.7.0'
          target: ${{ matrix.qt.target }}
          arch: ${{ matrix.qt.arch }}
